"""Add current_aya and monthly_fee to Student

Revision ID: 05db8d8c8ee4
Revises: 902c2146adec
Create Date: 2026-03-22 07:52:10.874403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05db8d8c8ee4'
down_revision = '902c2146adec'
branch_labels = None
depends_on = None


def upgrade():
    # Only keep the Student table changes to avoid migration failures due to DB inconsistencies
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_aya', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    
    # We will revisit other structural changes (indexes/FKs) later if needed.



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_ibfk_1', 'schools', ['school_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_Rays_machda_users_school_id'))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teachers_ibfk_2', 'schools', ['school_id'], ['id'])
        batch_op.create_foreign_key('teachers_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_teachers_school_id'))
        batch_op.create_index('employee_number', ['employee_number'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('system_settings_ibfk_1', 'schools', ['school_id'], ['id'])
        batch_op.create_index('uix_school_key', ['school_id', 'key'], unique=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subjects_school_id'))
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('code', ['code'], unique=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_ibfk_3', 'users', ['student_user_id'], ['id'])
        batch_op.create_foreign_key('students_ibfk_4', 'schools', ['school_id'], ['id'])
        batch_op.create_foreign_key('students_ibfk_2', 'users', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_students_school_id'))
        batch_op.drop_column('monthly_fee')
        batch_op.drop_column('current_aya')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Rays_machda_role_permissions_school_id'))

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('otps_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_Rays_machda_otps_school_id'))
        batch_op.create_index('idx_otp_school', ['school_id'], unique=False)

    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_message_logs_school_id'))
        batch_op.drop_column('school_id')
        batch_op.drop_column('provider_message_id')

    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('login_logs_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.create_index('idx_ll_school', ['school_id'], unique=False)

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fees_school_id'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_school_id'))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exams_school_id'))

    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exam_results_school_id'))

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_class_sessions_school_id'))

    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('class_schedules_ibfk_2', 'schools', ['school_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_class_schedules_school_id'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categories_school_id'))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attendance_school_id'))

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('announcements_ibfk_1', 'users', ['created_by_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_announcements_school_id'))

    # ### end Alembic commands ###
